"""sync_schema_with_models

Revision ID: 393ef8ac90d7
Revises: cb2b7ab12aa7
Create Date: 2026-04-13 17:58:17.594397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393ef8ac90d7'
down_revision: Union[str, None] = 'cb2b7ab12aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
