"""Add category, tags, and agent availability

Revision ID: cb2b7ab12aa7
Revises: f70ef2679800
Create Date: 2026-02-02 19:07:24.840701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2b7ab12aa7'
down_revision: Union[str, None] = 'f70ef2679800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_available')
    op.drop_column('tickets', 'tags')
    op.drop_column('tickets', 'category')
    # ### end Alembic commands ###
